# Site settings
title: Kayle Kaupanger
email: kaupakay000@gmail.com
url: http://kaylekaupanger.com/
description: "Kayle"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: NicholasResendez

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/stillkayle
  - title: twitter
    url: https://twitter.com/KayleKaupanger



# Build settings
markdown: kramdown
permalink: pretty
